# fly.toml app configuration file generated for findingway on 2023-06-10T09:14:57-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "findingway"
primary_region = "lax"

[build]
  image = "ghcr.io/veraticus/findingway:main"
